# Generated by Django 3.0.6 on 2020-05-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
